(() => {
  'use strict';
  const base='https://playertaza.csilvasantin.workers.dev', $=id=>document.getElementById(id);
  const aliases={canalkiosk:'canalkiosk-jardinets',colas:'starbucks-queue',yarigai:'yarigai'};
  let binding=null, trial=null, busy=false;
  const log=text=>{ $('terminal').textContent+='\n'+new Date().toLocaleTimeString()+' '+text; $('terminal').scrollTop=$('terminal').scrollHeight; };
  const say=text=>{ $('guidance').textContent=text; $('guide-avatar').contentWindow.postMessage({source:'ainimation-xperiencia',type:'say',text,lang:'es-ES'},'https://digitalavatar.ai'); log(text); };
  const pending=value=>{ $('test-confirm').disabled=$('test-fail').disabled=!value; };
  async function api(path,body){const r=await fetch(base+path,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok||d.ok===false)throw Error(d.error||d.message||'HTTP '+r.status);return d;}
  async function status(){const d=await api('/api/store-binding');binding=d.binding;$('association').textContent=binding?.enabled?binding.name+' · activo':'Sin proyecto activo';if(binding&&[...$('project').options].some(o=>o.value===binding.storeId))$('project').value=binding.storeId;$('diagnostics').textContent=JSON.stringify(d,null,2);return binding;}
  async function project(value){const id=aliases[value]||value;if(!Object.values(aliases).includes(id))throw Error('Proyecto desconocido. Usa canalkiosk, colas o yarigai.');await api('/api/store-binding',{storeId:id,screen:''});trial=null;pending(false);await status();say('Proyecto activo: '+binding.name+'. Ya puedes iniciar una prueba.');}
  async function test(){await status();if(!binding?.enabled)throw Error('Activa primero un proyecto.');trial={revision:binding.revision,project:binding.project};pending(false);if(binding.project==='starbucks-queue'){const marker='TEST '+String(Date.now()).slice(-4);const d=await api('/api/mug-status',{project:'starbucks-queue',via:'queue-follow',source:'gestorColas',name:marker,verb:'LISTO'});if(!d.bubble?.queued){trial=null;throw Error('La prueba no ha quedado encolada. '+JSON.stringify(d.bubble||{}));}trial.expected=marker+' LISTO';say('Envío en cola. Busca '+trial.expected+' en la taza usando la cámara. Confirma solo cuando coincida.');}else{trial.expected='contenido seleccionado en '+binding.name;say('Cambia el contenido en '+binding.name+'. Espera a verlo en la cámara de la taza y pulsa «Lo veo en la taza».');}pending(true);}
  async function confirm(ok){if(!trial)throw Error('Inicia primero una prueba.');await status();if(binding?.revision!==trial.revision){trial=null;pending(false);throw Error('El proyecto ha cambiado. Inicia una nueva prueba.');}say(ok?'Comprobación visual confirmada por el operador: '+trial.expected+'.':'El operador indica que no coincide. Revisa el puente y la conexión CarlosGdG en Bubble.');trial=null;pending(false);}
  async function run(raw){if(busy)return;busy=true;log('› '+raw);try{const [cmd,...args]=raw.trim().split(/\s+/);switch(cmd.toLowerCase()){case 'help':log('status: asociación actual\nproject canalkiosk|colas|yarigai: cambia el proyecto compartido\ntest: guía una prueba (en colas envía un marcador)\nconfirm / fail: registra tu comprobación visual\nclear: limpia el registro');break;case 'status':log(JSON.stringify(await status(),null,2));break;case 'project':await project(args[0]);break;case 'test':await test();break;case 'confirm':await confirm(true);break;case 'fail':await confirm(false);break;case 'clear':$('terminal').textContent='';break;default:throw Error('Comando desconocido. Escribe help.');}}catch(e){if(raw.trim().toLowerCase()==='test'){trial=null;pending(false);}say('Error: '+e.message);}finally{busy=false;}}
  document.querySelectorAll('[data-panel]').forEach(b=>{b.setAttribute('aria-expanded','false');b.addEventListener('click',()=>{const p=$(b.dataset.panel);p.hidden=!p.hidden;b.setAttribute('aria-expanded',String(!p.hidden));if(!p.hidden&&p.id==='expert')$('command').focus();});});
  function close(p){p.hidden=true;const b=document.querySelector('[data-panel="'+p.id+'"]');b.setAttribute('aria-expanded','false');b.focus();}
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.closest('aside')));
  document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.control-panel:not([hidden])').forEach(close);});
  $('command-form').onsubmit=e=>{e.preventDefault();const command=$('command').value;$('command').value='';run(command);};
  $('associate').onclick=()=>run('project '+$('project').value);$('test-start').onclick=()=>run('test');$('test-confirm').onclick=()=>run('confirm');$('test-fail').onclick=()=>run('fail');
  status().catch(e=>say('No se puede consultar la asociación: '+e.message));
})();
